version: '3.9'

services:
  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations  
    networks:
      - custom_network

  carpetwash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carpetwash
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8082:7981
    networks:
      - custom_network

networks:
  custom_network:  
    external: true  
