version: '3.9'

services:
  carpetwash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carpetwash
    ports:
      - 8082:7981
    networks:
      - custom_network

networks:
  custom_network:  
    external: true  
