// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Address struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Latitude  sql.NullString
	Longitude sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Company struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Order struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	ServiceID uuid.NullUUID
	AddressID uuid.NullUUID
	CreatedAt sql.NullTime
}

type Service struct {
	ID          uuid.UUID
	Tariffs     sql.NullString
	CompanyID   int32
	Name        string
	Description sql.NullString
	Price       sql.NullString
}
