// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO  company (id,name, description) 
VALUES ($1, $2, $3)
RETURNING id, name, description
`

type CreateCompanyParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type CreateCompanyRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.ID, arg.Name, arg.Description)
	var i CreateCompanyRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
